[env:esp32doit-devkit-v1]
; Use the upstream platform version which supports Arduino 3.0.0+
platform = https://github.com/platformio/platform-espressif32.git
board = esp32doit-devkit-v1
framework = arduino

build_flags =
  ; Local library includes
  -I lib/TFT_eSPI
  -I lib/ESP_I2S
  -I lib/ESP_NOW
  -I lib/FS
  -I lib/SD
  ; Display configuration
  -D USER_SETUP_LOADED=1
  -D ILI9341_DRIVER=1        
  -D TFT_MISO=19
  -D TFT_MOSI=23
  -D TFT_SCLK=18
  -D TFT_CS=5
  -D TFT_DC=2
  -D TFT_RST=4
  -D LOAD_GLCD=1               
  -D SPI_FREQUENCY=27000000
  -D LOAD_FONT2=1