[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
lib_ldf_mode = deep
lib_deps = 
    bodmer/TFT_eSPI
    ESP32 I2S

build_flags =
  ; Display configuration
  -D USER_SETUP_LOADED=1
  -D ST7796_DRIVER=1        
  -D TFT_MISO=19
  -D TFT_MOSI=23
  -D TFT_SCLK=18
  -D TFT_CS=5
  -D TFT_DC=2
  -D TFT_RST=4
  -D LOAD_GLCD=1               
  -D SPI_FREQUENCY=27000000
  -D LOAD_FONT2=1